import tensorflow as tf

sess = tf.Session()
a = tf.Variable([1, 2, 3])
b = tf.Variable([2, 1.0, 4.0])
c = tf.Variable([2, 1.0, 0.0])
d = tf.Variable([2, 0.0, 4.0])
e = tf.Variable([0, 1.0, 4.0])
f = tf.Variable([0, 1.0, 0.0])
g = tf.Variable([0, 0.0, 0.0])

sess.run(tf.global_variables_initializer())
print("a: ", sess.run(a))
print("b: ", sess.run(b))
print("c: ", sess.run(c))
print("d: ", sess.run(d))
print("e: ", sess.run(e))
print("f: ", sess.run(f))
print("g: ", sess.run(g))
# c = tf.maximum(a, b)
a1 = tf.boolean_mask(a, b)
a2 = tf.boolean_mask(a, c)
a3 = tf.boolean_mask(a, d)
a4 = tf.boolean_mask(a, e)
a5 = tf.boolean_mask(a, f)
a6 = tf.boolean_mask(a, g)

print("tf.boolean(a, b):\n  ", sess.run(a1))
print("tf.boolean(a, c):\n  ", sess.run(a2))
print("tf.boolean(a, d):\n  ", sess.run(a3))
print("tf.boolean(a, e):\n  ", sess.run(a4))
print("tf.boolean(a, f):\n  ", sess.run(a5))
print("tf.boolean(a, g):\n  ", sess.run(a6))

