#! /bin/bash

# creat some files
echo "file one" > file1
echo "file two" > file2
echo "file three" > file3

# print their contents
a=`cat file1`
b=`cat file2`
c=`cat file3`
echo $a
echo $b
echo $c

# concatenate these files
cat $(ls file[0-9]) > file

# print the concatenate file
all=`cat file`
echo $all

# delete these files
rm file1
rm file2
rm file3
rm file
